export { MotorInteger, MotorInt32 } from "./type/integer.type";
export { MotorShort, MotorInt16 } from "./type/short.type";
export { MotorInt8 } from "./type/int8.type";
export { MotorLong, MotorInt64 } from "./type/long.type";
export { MotorFloat, MotorFloat32 } from "./type/float.type";
export { MotorDouble, MotorFloat64 } from "./type/double.type";
export { MotorUnsignedInt8, MotorUint8 } from "./type/unsigned-int8.type";
export { MotorUnsignedShort, MotorUint16 } from "./type/unsigned-short.type";
export { MotorUnsignedInteger, MotorUint32 } from "./type/unsigned-integer.type";
export { MotorUnsignedLong, MotorUint64 as MotorUInt64 } from "./type/unsigned-long.type";
export { MotorBool } from "./type/bool.type";
export { MotorArray } from "./type/array.type";
export { MotorStruct } from "./type/struct.type";
export { MotorString } from "./type/references/string.ref";
export { MotorList } from "./type/references/list.ref";
export { MotorInstance } from "./instance";
export { MotorMemory } from "./memory";
export { MotorType } from "./type";
export { MotorNull } from "./type/null.type";
